// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.11.4
// source: fulfillment/v1/fulfillment.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of fulfillment method chosen for the order.
type FulfillmentType int32

const (
	FulfillmentType_FULFILLMENT_TYPE_UNSPECIFIED  FulfillmentType = 0
	FulfillmentType_FULFILLMENT_TYPE_SHIPPING     FulfillmentType = 1
	FulfillmentType_FULFILLMENT_TYPE_LOCAL_PICKUP FulfillmentType = 2
)

// Enum value maps for FulfillmentType.
var (
	FulfillmentType_name = map[int32]string{
		0: "FULFILLMENT_TYPE_UNSPECIFIED",
		1: "FULFILLMENT_TYPE_SHIPPING",
		2: "FULFILLMENT_TYPE_LOCAL_PICKUP",
	}
	FulfillmentType_value = map[string]int32{
		"FULFILLMENT_TYPE_UNSPECIFIED":  0,
		"FULFILLMENT_TYPE_SHIPPING":     1,
		"FULFILLMENT_TYPE_LOCAL_PICKUP": 2,
	}
)

func (x FulfillmentType) Enum() *FulfillmentType {
	p := new(FulfillmentType)
	*p = x
	return p
}

func (x FulfillmentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FulfillmentType) Descriptor() protoreflect.EnumDescriptor {
	return file_fulfillment_v1_fulfillment_proto_enumTypes[0].Descriptor()
}

func (FulfillmentType) Type() protoreflect.EnumType {
	return &file_fulfillment_v1_fulfillment_proto_enumTypes[0]
}

func (x FulfillmentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FulfillmentType.Descriptor instead.
func (FulfillmentType) EnumDescriptor() ([]byte, []int) {
	return file_fulfillment_v1_fulfillment_proto_rawDescGZIP(), []int{0}
}

// Current status of the physical fulfillment.
type FulfillmentStatus int32

const (
	FulfillmentStatus_FULFILLMENT_STATUS_UNSPECIFIED      FulfillmentStatus = 0
	FulfillmentStatus_FULFILLMENT_STATUS_PREPARING        FulfillmentStatus = 1
	FulfillmentStatus_FULFILLMENT_STATUS_READY_FOR_PICKUP FulfillmentStatus = 2
	FulfillmentStatus_FULFILLMENT_STATUS_IN_TRANSIT       FulfillmentStatus = 3
	FulfillmentStatus_FULFILLMENT_STATUS_DELIVERED        FulfillmentStatus = 4
	FulfillmentStatus_FULFILLMENT_STATUS_PICKED_UP        FulfillmentStatus = 5
	FulfillmentStatus_FULFILLMENT_STATUS_EXCEPTION        FulfillmentStatus = 6
)

// Enum value maps for FulfillmentStatus.
var (
	FulfillmentStatus_name = map[int32]string{
		0: "FULFILLMENT_STATUS_UNSPECIFIED",
		1: "FULFILLMENT_STATUS_PREPARING",
		2: "FULFILLMENT_STATUS_READY_FOR_PICKUP",
		3: "FULFILLMENT_STATUS_IN_TRANSIT",
		4: "FULFILLMENT_STATUS_DELIVERED",
		5: "FULFILLMENT_STATUS_PICKED_UP",
		6: "FULFILLMENT_STATUS_EXCEPTION",
	}
	FulfillmentStatus_value = map[string]int32{
		"FULFILLMENT_STATUS_UNSPECIFIED":      0,
		"FULFILLMENT_STATUS_PREPARING":        1,
		"FULFILLMENT_STATUS_READY_FOR_PICKUP": 2,
		"FULFILLMENT_STATUS_IN_TRANSIT":       3,
		"FULFILLMENT_STATUS_DELIVERED":        4,
		"FULFILLMENT_STATUS_PICKED_UP":        5,
		"FULFILLMENT_STATUS_EXCEPTION":        6,
	}
)

func (x FulfillmentStatus) Enum() *FulfillmentStatus {
	p := new(FulfillmentStatus)
	*p = x
	return p
}

func (x FulfillmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FulfillmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_fulfillment_v1_fulfillment_proto_enumTypes[1].Descriptor()
}

func (FulfillmentStatus) Type() protoreflect.EnumType {
	return &file_fulfillment_v1_fulfillment_proto_enumTypes[1]
}

func (x FulfillmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FulfillmentStatus.Descriptor instead.
func (FulfillmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_fulfillment_v1_fulfillment_proto_rawDescGZIP(), []int{1}
}

// Fulfillment represents how an order gets to the customer (shipping or local store pickup).
type Fulfillment struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Type    FulfillmentType        `protobuf:"varint,3,opt,name=type,proto3,enum=fulfillment.v1.FulfillmentType" json:"type,omitempty"`
	Status  FulfillmentStatus      `protobuf:"varint,4,opt,name=status,proto3,enum=fulfillment.v1.FulfillmentStatus" json:"status,omitempty"`
	// Populated if type == FULFILLMENT_TYPE_SHIPPING
	ShipmentDetails *ShipmentDetails `protobuf:"bytes,5,opt,name=shipment_details,json=shipmentDetails,proto3" json:"shipment_details,omitempty"`
	// Populated if type == FULFILLMENT_TYPE_LOCAL_PICKUP
	PickupDetails *PickupDetails `protobuf:"bytes,6,opt,name=pickup_details,json=pickupDetails,proto3" json:"pickup_details,omitempty"`
	CreatedAt     string         `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string         `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fulfillment) Reset() {
	*x = Fulfillment{}
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fulfillment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fulfillment) ProtoMessage() {}

func (x *Fulfillment) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fulfillment.ProtoReflect.Descriptor instead.
func (*Fulfillment) Descriptor() ([]byte, []int) {
	return file_fulfillment_v1_fulfillment_proto_rawDescGZIP(), []int{0}
}

func (x *Fulfillment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Fulfillment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Fulfillment) GetType() FulfillmentType {
	if x != nil {
		return x.Type
	}
	return FulfillmentType_FULFILLMENT_TYPE_UNSPECIFIED
}

func (x *Fulfillment) GetStatus() FulfillmentStatus {
	if x != nil {
		return x.Status
	}
	return FulfillmentStatus_FULFILLMENT_STATUS_UNSPECIFIED
}

func (x *Fulfillment) GetShipmentDetails() *ShipmentDetails {
	if x != nil {
		return x.ShipmentDetails
	}
	return nil
}

func (x *Fulfillment) GetPickupDetails() *PickupDetails {
	if x != nil {
		return x.PickupDetails
	}
	return nil
}

func (x *Fulfillment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Fulfillment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Specifics for a carrier-based delivery.
type ShipmentDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TrackingNumber    string                 `protobuf:"bytes,1,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Carrier           string                 `protobuf:"bytes,2,opt,name=carrier,proto3" json:"carrier,omitempty"` // e.g., "UPS", "FedEx", "USPS"
	EstimatedDelivery string                 `protobuf:"bytes,3,opt,name=estimated_delivery,json=estimatedDelivery,proto3" json:"estimated_delivery,omitempty"`
	Destination       *ShippingAddress       `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ShipmentDetails) Reset() {
	*x = ShipmentDetails{}
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentDetails) ProtoMessage() {}

func (x *ShipmentDetails) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentDetails.ProtoReflect.Descriptor instead.
func (*ShipmentDetails) Descriptor() ([]byte, []int) {
	return file_fulfillment_v1_fulfillment_proto_rawDescGZIP(), []int{1}
}

func (x *ShipmentDetails) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *ShipmentDetails) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *ShipmentDetails) GetEstimatedDelivery() string {
	if x != nil {
		return x.EstimatedDelivery
	}
	return ""
}

func (x *ShipmentDetails) GetDestination() *ShippingAddress {
	if x != nil {
		return x.Destination
	}
	return nil
}

// Specifics for a Buy Online, Pick Up In Store (BOPIS) order.
type PickupDetails struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StoreId            string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	PickupInstructions string                 `protobuf:"bytes,2,opt,name=pickup_instructions,json=pickupInstructions,proto3" json:"pickup_instructions,omitempty"`
	PickupTime         string                 `protobuf:"bytes,3,opt,name=pickup_time,json=pickupTime,proto3" json:"pickup_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PickupDetails) Reset() {
	*x = PickupDetails{}
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickupDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickupDetails) ProtoMessage() {}

func (x *PickupDetails) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickupDetails.ProtoReflect.Descriptor instead.
func (*PickupDetails) Descriptor() ([]byte, []int) {
	return file_fulfillment_v1_fulfillment_proto_rawDescGZIP(), []int{2}
}

func (x *PickupDetails) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *PickupDetails) GetPickupInstructions() string {
	if x != nil {
		return x.PickupInstructions
	}
	return ""
}

func (x *PickupDetails) GetPickupTime() string {
	if x != nil {
		return x.PickupTime
	}
	return ""
}

// Basic address representation used strictly for routing.
type ShippingAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Zip           string                 `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingAddress) Reset() {
	*x = ShippingAddress{}
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingAddress) ProtoMessage() {}

func (x *ShippingAddress) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingAddress.ProtoReflect.Descriptor instead.
func (*ShippingAddress) Descriptor() ([]byte, []int) {
	return file_fulfillment_v1_fulfillment_proto_rawDescGZIP(), []int{3}
}

func (x *ShippingAddress) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *ShippingAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ShippingAddress) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ShippingAddress) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

func (x *ShippingAddress) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// Request to initialize the fulfillment process for an order.
type CreateFulfillmentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Type            FulfillmentType        `protobuf:"varint,2,opt,name=type,proto3,enum=fulfillment.v1.FulfillmentType" json:"type,omitempty"` // Must be Shipping or Pickup
	ShipmentDetails *ShipmentDetails       `protobuf:"bytes,3,opt,name=shipment_details,json=shipmentDetails,proto3" json:"shipment_details,omitempty"`
	PickupDetails   *PickupDetails         `protobuf:"bytes,4,opt,name=pickup_details,json=pickupDetails,proto3" json:"pickup_details,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateFulfillmentRequest) Reset() {
	*x = CreateFulfillmentRequest{}
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFulfillmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFulfillmentRequest) ProtoMessage() {}

func (x *CreateFulfillmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFulfillmentRequest.ProtoReflect.Descriptor instead.
func (*CreateFulfillmentRequest) Descriptor() ([]byte, []int) {
	return file_fulfillment_v1_fulfillment_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFulfillmentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateFulfillmentRequest) GetType() FulfillmentType {
	if x != nil {
		return x.Type
	}
	return FulfillmentType_FULFILLMENT_TYPE_UNSPECIFIED
}

func (x *CreateFulfillmentRequest) GetShipmentDetails() *ShipmentDetails {
	if x != nil {
		return x.ShipmentDetails
	}
	return nil
}

func (x *CreateFulfillmentRequest) GetPickupDetails() *PickupDetails {
	if x != nil {
		return x.PickupDetails
	}
	return nil
}

// Response mapping the newly registered Fulfillment record.
type CreateFulfillmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fulfillment   *Fulfillment           `protobuf:"bytes,1,opt,name=fulfillment,proto3" json:"fulfillment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFulfillmentResponse) Reset() {
	*x = CreateFulfillmentResponse{}
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFulfillmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFulfillmentResponse) ProtoMessage() {}

func (x *CreateFulfillmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFulfillmentResponse.ProtoReflect.Descriptor instead.
func (*CreateFulfillmentResponse) Descriptor() ([]byte, []int) {
	return file_fulfillment_v1_fulfillment_proto_rawDescGZIP(), []int{5}
}

func (x *CreateFulfillmentResponse) GetFulfillment() *Fulfillment {
	if x != nil {
		return x.Fulfillment
	}
	return nil
}

// Request to fetch tracking or pickup statuses.
type GetFulfillmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFulfillmentRequest) Reset() {
	*x = GetFulfillmentRequest{}
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFulfillmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFulfillmentRequest) ProtoMessage() {}

func (x *GetFulfillmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFulfillmentRequest.ProtoReflect.Descriptor instead.
func (*GetFulfillmentRequest) Descriptor() ([]byte, []int) {
	return file_fulfillment_v1_fulfillment_proto_rawDescGZIP(), []int{6}
}

func (x *GetFulfillmentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Response returning the current Fulfillment state.
type GetFulfillmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fulfillment   *Fulfillment           `protobuf:"bytes,1,opt,name=fulfillment,proto3" json:"fulfillment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFulfillmentResponse) Reset() {
	*x = GetFulfillmentResponse{}
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFulfillmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFulfillmentResponse) ProtoMessage() {}

func (x *GetFulfillmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFulfillmentResponse.ProtoReflect.Descriptor instead.
func (*GetFulfillmentResponse) Descriptor() ([]byte, []int) {
	return file_fulfillment_v1_fulfillment_proto_rawDescGZIP(), []int{7}
}

func (x *GetFulfillmentResponse) GetFulfillment() *Fulfillment {
	if x != nil {
		return x.Fulfillment
	}
	return nil
}

// Request to update the lifecycle status of a package/pickup (e.g., IN_TRANSIT, READY_FOR_PICKUP).
type UpdateFulfillmentStatusRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status FulfillmentStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=fulfillment.v1.FulfillmentStatus" json:"status,omitempty"`
	// Optional field to append tracking info if the carrier updates it.
	TrackingNumber string `protobuf:"bytes,3,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateFulfillmentStatusRequest) Reset() {
	*x = UpdateFulfillmentStatusRequest{}
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFulfillmentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFulfillmentStatusRequest) ProtoMessage() {}

func (x *UpdateFulfillmentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFulfillmentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateFulfillmentStatusRequest) Descriptor() ([]byte, []int) {
	return file_fulfillment_v1_fulfillment_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateFulfillmentStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateFulfillmentStatusRequest) GetStatus() FulfillmentStatus {
	if x != nil {
		return x.Status
	}
	return FulfillmentStatus_FULFILLMENT_STATUS_UNSPECIFIED
}

func (x *UpdateFulfillmentStatusRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

// Response after updating a fulfillment status.
type UpdateFulfillmentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fulfillment   *Fulfillment           `protobuf:"bytes,1,opt,name=fulfillment,proto3" json:"fulfillment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFulfillmentStatusResponse) Reset() {
	*x = UpdateFulfillmentStatusResponse{}
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFulfillmentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFulfillmentStatusResponse) ProtoMessage() {}

func (x *UpdateFulfillmentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_fulfillment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFulfillmentStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateFulfillmentStatusResponse) Descriptor() ([]byte, []int) {
	return file_fulfillment_v1_fulfillment_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateFulfillmentStatusResponse) GetFulfillment() *Fulfillment {
	if x != nil {
		return x.Fulfillment
	}
	return nil
}

var File_fulfillment_v1_fulfillment_proto protoreflect.FileDescriptor

const file_fulfillment_v1_fulfillment_proto_rawDesc = "" +
	"\n" +
	" fulfillment/v1/fulfillment.proto\x12\x0efulfillment.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\"\xa0\x03\n" +
	"\vFulfillment\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\x12#\n" +
	"\border_id\x18\x02 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\aorderId\x12=\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1f.fulfillment.v1.FulfillmentTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\x04type\x12C\n" +
	"\x06status\x18\x04 \x01(\x0e2!.fulfillment.v1.FulfillmentStatusB\b\xfaB\x05\x82\x01\x02\x10\x01R\x06status\x12J\n" +
	"\x10shipment_details\x18\x05 \x01(\v2\x1f.fulfillment.v1.ShipmentDetailsR\x0fshipmentDetails\x12D\n" +
	"\x0epickup_details\x18\x06 \x01(\v2\x1d.fulfillment.v1.PickupDetailsR\rpickupDetails\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\xd0\x01\n" +
	"\x0fShipmentDetails\x12'\n" +
	"\x0ftracking_number\x18\x01 \x01(\tR\x0etrackingNumber\x12\x18\n" +
	"\acarrier\x18\x02 \x01(\tR\acarrier\x12-\n" +
	"\x12estimated_delivery\x18\x03 \x01(\tR\x11estimatedDelivery\x12K\n" +
	"\vdestination\x18\x04 \x01(\v2\x1f.fulfillment.v1.ShippingAddressB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vdestination\"\x85\x01\n" +
	"\rPickupDetails\x12\"\n" +
	"\bstore_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\astoreId\x12/\n" +
	"\x13pickup_instructions\x18\x02 \x01(\tR\x12pickupInstructions\x12\x1f\n" +
	"\vpickup_time\x18\x03 \x01(\tR\n" +
	"pickupTime\"\xad\x01\n" +
	"\x0fShippingAddress\x12\x1f\n" +
	"\x06street\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06street\x12\x1b\n" +
	"\x04city\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04city\x12\x1d\n" +
	"\x05state\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05state\x12\x19\n" +
	"\x03zip\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x03zip\x12\"\n" +
	"\acountry\x18\x05 \x01(\tB\b\xfaB\x05r\x03\x98\x01\x02R\acountry\"\x92\x02\n" +
	"\x18CreateFulfillmentRequest\x12#\n" +
	"\border_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\aorderId\x12?\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.fulfillment.v1.FulfillmentTypeB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\x04type\x12J\n" +
	"\x10shipment_details\x18\x03 \x01(\v2\x1f.fulfillment.v1.ShipmentDetailsR\x0fshipmentDetails\x12D\n" +
	"\x0epickup_details\x18\x04 \x01(\v2\x1d.fulfillment.v1.PickupDetailsR\rpickupDetails\"Z\n" +
	"\x19CreateFulfillmentResponse\x12=\n" +
	"\vfulfillment\x18\x01 \x01(\v2\x1b.fulfillment.v1.FulfillmentR\vfulfillment\"0\n" +
	"\x15GetFulfillmentRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\"W\n" +
	"\x16GetFulfillmentResponse\x12=\n" +
	"\vfulfillment\x18\x01 \x01(\v2\x1b.fulfillment.v1.FulfillmentR\vfulfillment\"\xa9\x01\n" +
	"\x1eUpdateFulfillmentStatusRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12E\n" +
	"\x06status\x18\x02 \x01(\x0e2!.fulfillment.v1.FulfillmentStatusB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\x06status\x12'\n" +
	"\x0ftracking_number\x18\x03 \x01(\tR\x0etrackingNumber\"`\n" +
	"\x1fUpdateFulfillmentStatusResponse\x12=\n" +
	"\vfulfillment\x18\x01 \x01(\v2\x1b.fulfillment.v1.FulfillmentR\vfulfillment*u\n" +
	"\x0fFulfillmentType\x12 \n" +
	"\x1cFULFILLMENT_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19FULFILLMENT_TYPE_SHIPPING\x10\x01\x12!\n" +
	"\x1dFULFILLMENT_TYPE_LOCAL_PICKUP\x10\x02*\x8b\x02\n" +
	"\x11FulfillmentStatus\x12\"\n" +
	"\x1eFULFILLMENT_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cFULFILLMENT_STATUS_PREPARING\x10\x01\x12'\n" +
	"#FULFILLMENT_STATUS_READY_FOR_PICKUP\x10\x02\x12!\n" +
	"\x1dFULFILLMENT_STATUS_IN_TRANSIT\x10\x03\x12 \n" +
	"\x1cFULFILLMENT_STATUS_DELIVERED\x10\x04\x12 \n" +
	"\x1cFULFILLMENT_STATUS_PICKED_UP\x10\x05\x12 \n" +
	"\x1cFULFILLMENT_STATUS_EXCEPTION\x10\x062\xc2\x03\n" +
	"\x12FulfillmentService\x12\x85\x01\n" +
	"\x11CreateFulfillment\x12(.fulfillment.v1.CreateFulfillmentRequest\x1a).fulfillment.v1.CreateFulfillmentResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/fulfillments\x12~\n" +
	"\x0eGetFulfillment\x12%.fulfillment.v1.GetFulfillmentRequest\x1a&.fulfillment.v1.GetFulfillmentResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/fulfillments/{id}\x12\xa3\x01\n" +
	"\x17UpdateFulfillmentStatus\x12..fulfillment.v1.UpdateFulfillmentStatusRequest\x1a/.fulfillment.v1.UpdateFulfillmentStatusResponse\"'\x82\xd3\xe4\x93\x02!:\x01*2\x1c/v1/fulfillments/{id}/statusB=Z;github.com/optimatelabs/tiny-go-commerce/pkg/fulfillment/v1b\x06proto3"

var (
	file_fulfillment_v1_fulfillment_proto_rawDescOnce sync.Once
	file_fulfillment_v1_fulfillment_proto_rawDescData []byte
)

func file_fulfillment_v1_fulfillment_proto_rawDescGZIP() []byte {
	file_fulfillment_v1_fulfillment_proto_rawDescOnce.Do(func() {
		file_fulfillment_v1_fulfillment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fulfillment_v1_fulfillment_proto_rawDesc), len(file_fulfillment_v1_fulfillment_proto_rawDesc)))
	})
	return file_fulfillment_v1_fulfillment_proto_rawDescData
}

var file_fulfillment_v1_fulfillment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fulfillment_v1_fulfillment_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_fulfillment_v1_fulfillment_proto_goTypes = []any{
	(FulfillmentType)(0),                    // 0: fulfillment.v1.FulfillmentType
	(FulfillmentStatus)(0),                  // 1: fulfillment.v1.FulfillmentStatus
	(*Fulfillment)(nil),                     // 2: fulfillment.v1.Fulfillment
	(*ShipmentDetails)(nil),                 // 3: fulfillment.v1.ShipmentDetails
	(*PickupDetails)(nil),                   // 4: fulfillment.v1.PickupDetails
	(*ShippingAddress)(nil),                 // 5: fulfillment.v1.ShippingAddress
	(*CreateFulfillmentRequest)(nil),        // 6: fulfillment.v1.CreateFulfillmentRequest
	(*CreateFulfillmentResponse)(nil),       // 7: fulfillment.v1.CreateFulfillmentResponse
	(*GetFulfillmentRequest)(nil),           // 8: fulfillment.v1.GetFulfillmentRequest
	(*GetFulfillmentResponse)(nil),          // 9: fulfillment.v1.GetFulfillmentResponse
	(*UpdateFulfillmentStatusRequest)(nil),  // 10: fulfillment.v1.UpdateFulfillmentStatusRequest
	(*UpdateFulfillmentStatusResponse)(nil), // 11: fulfillment.v1.UpdateFulfillmentStatusResponse
}
var file_fulfillment_v1_fulfillment_proto_depIdxs = []int32{
	0,  // 0: fulfillment.v1.Fulfillment.type:type_name -> fulfillment.v1.FulfillmentType
	1,  // 1: fulfillment.v1.Fulfillment.status:type_name -> fulfillment.v1.FulfillmentStatus
	3,  // 2: fulfillment.v1.Fulfillment.shipment_details:type_name -> fulfillment.v1.ShipmentDetails
	4,  // 3: fulfillment.v1.Fulfillment.pickup_details:type_name -> fulfillment.v1.PickupDetails
	5,  // 4: fulfillment.v1.ShipmentDetails.destination:type_name -> fulfillment.v1.ShippingAddress
	0,  // 5: fulfillment.v1.CreateFulfillmentRequest.type:type_name -> fulfillment.v1.FulfillmentType
	3,  // 6: fulfillment.v1.CreateFulfillmentRequest.shipment_details:type_name -> fulfillment.v1.ShipmentDetails
	4,  // 7: fulfillment.v1.CreateFulfillmentRequest.pickup_details:type_name -> fulfillment.v1.PickupDetails
	2,  // 8: fulfillment.v1.CreateFulfillmentResponse.fulfillment:type_name -> fulfillment.v1.Fulfillment
	2,  // 9: fulfillment.v1.GetFulfillmentResponse.fulfillment:type_name -> fulfillment.v1.Fulfillment
	1,  // 10: fulfillment.v1.UpdateFulfillmentStatusRequest.status:type_name -> fulfillment.v1.FulfillmentStatus
	2,  // 11: fulfillment.v1.UpdateFulfillmentStatusResponse.fulfillment:type_name -> fulfillment.v1.Fulfillment
	6,  // 12: fulfillment.v1.FulfillmentService.CreateFulfillment:input_type -> fulfillment.v1.CreateFulfillmentRequest
	8,  // 13: fulfillment.v1.FulfillmentService.GetFulfillment:input_type -> fulfillment.v1.GetFulfillmentRequest
	10, // 14: fulfillment.v1.FulfillmentService.UpdateFulfillmentStatus:input_type -> fulfillment.v1.UpdateFulfillmentStatusRequest
	7,  // 15: fulfillment.v1.FulfillmentService.CreateFulfillment:output_type -> fulfillment.v1.CreateFulfillmentResponse
	9,  // 16: fulfillment.v1.FulfillmentService.GetFulfillment:output_type -> fulfillment.v1.GetFulfillmentResponse
	11, // 17: fulfillment.v1.FulfillmentService.UpdateFulfillmentStatus:output_type -> fulfillment.v1.UpdateFulfillmentStatusResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_fulfillment_v1_fulfillment_proto_init() }
func file_fulfillment_v1_fulfillment_proto_init() {
	if File_fulfillment_v1_fulfillment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fulfillment_v1_fulfillment_proto_rawDesc), len(file_fulfillment_v1_fulfillment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fulfillment_v1_fulfillment_proto_goTypes,
		DependencyIndexes: file_fulfillment_v1_fulfillment_proto_depIdxs,
		EnumInfos:         file_fulfillment_v1_fulfillment_proto_enumTypes,
		MessageInfos:      file_fulfillment_v1_fulfillment_proto_msgTypes,
	}.Build()
	File_fulfillment_v1_fulfillment_proto = out.File
	file_fulfillment_v1_fulfillment_proto_goTypes = nil
	file_fulfillment_v1_fulfillment_proto_depIdxs = nil
}
